### ISSUE TITLE
Setup Node step failing when in subfolder

### ISSUE THREAD

**Issue by omar-h-omar** [withastro/action#20]
Hi there I noticed that the Setup Node step is missing `cache-dependency-path`. Without this, if the user provides a path to a subfolder the build will fail as node won't be able to find the lockfiles since they are in the subfolder. Here's a picture of a build failing because of this issue:
<img width="1306" alt="Screenshot 2023-01-26 at 11 32 58 am" src="https://user-images.githubusercontent.com/58376513/214825561-b3969772-bfe6-4122-bbdc-34be920c1118.png">

**Comment by spencerrais** [comment]
I am also running into the same issue.

**Comment by natemoo-re** [comment]
This should be fixed in the latest ([v0.2.0](https://github.com/withastro/action/releases/tag/v0.2.0))

**Comment by rajat1saxena** [comment]
This caused #21 for me. Anyway to disable it?
