### ISSUE TITLE
Error: Some specified paths were not resolved, unable to cache dependencies.

### ISSUE THREAD

**Issue by rajat1saxena** [withastro/action#21]
Hi,

Thanks for this project. I am unable to deploy my documentation site using this action. I am getting the following error.

```
Error: Some specified paths were not resolved, unable to cache dependencies.
```

I think it is coming due to the fact that setup-node is trying to locate the cache inside apps/docs folder but since it is a monorepo, it is located two levels up.

From the job run, I noticed this:

```
cache-dependency-path: ./apps/docs/yarn.lock
```

There is no `yarn.lock` inside `apps/docs` since this is a monorepo.

Github job: https://github.com/codelitdev/courselit/actions/runs/4132972124/jobs/7142310620

Before today, it was working fine.

**Comment by ZhouYue8** [comment]
why
