### ISSUE TITLE
How to set environment variables before building?

### ISSUE THREAD

**Issue by Yekna** [withastro/action#39]
I'm having a problem understanding how exactly it is I'm supposed to set the environment variables for my astro project that i'm deploying to github pages. I've set an environment variable inside my github repo but from what I understand it's not accessible through withastro/action@v1

**Comment by natemoo-re** [comment]
Hey @Yekna! Sorry, we don't often check this repository's issues. 

I'd recommend joining us in the [Astro Discord](https://astro.build/chat) for further support. We have a `#support` channel where folks would be more than happy to help you with your specific issue!
