### ISSUE TITLE
Allow Specifying Versions of setup-node and upload-pages-artifact

### ISSUE THREAD

**Issue by taylorfsteele** [withastro/action#44]
Hey folks, I just tried to use this action in a GHES environment and wasn't able to because the versions of `setup-node` and `upload-pages-artifact` aren't supported on my GHES version.

It would be great if I could specify which versions of these actions to allow compatibility with GHES.

Thanks!

**Comment by natemoo-re** [comment]
This is probably best solved by us keeping the action up-to-date rather than introducing a new user-facing setting! 

We were a bit slow on getting [`v2.0.0`](https://github.com/withastro/action/releases/tag/v2.0.0) out, but this should be fixed as of #41.
